// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_RcppKagome_RCPPEXPORTS_H_GEN_
#define RCPP_RcppKagome_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace RcppKagome {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("RcppKagome", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("RcppKagome", "_RcppKagome_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in RcppKagome");
            }
        }
    }

    inline Rcpp::CharacterVector tokenize_morphemes(Rcpp::CharacterVector text) {
        typedef SEXP(*Ptr_tokenize_morphemes)(SEXP);
        static Ptr_tokenize_morphemes p_tokenize_morphemes = NULL;
        if (p_tokenize_morphemes == NULL) {
            validateSignature("Rcpp::CharacterVector(*tokenize_morphemes)(Rcpp::CharacterVector)");
            p_tokenize_morphemes = (Ptr_tokenize_morphemes)R_GetCCallable("RcppKagome", "_RcppKagome_tokenize_morphemes");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_tokenize_morphemes(Shield<SEXP>(Rcpp::wrap(text)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::CharacterVector >(rcpp_result_gen);
    }

    inline Rcpp::List tokenize_sentences(Rcpp::CharacterVector text) {
        typedef SEXP(*Ptr_tokenize_sentences)(SEXP);
        static Ptr_tokenize_sentences p_tokenize_sentences = NULL;
        if (p_tokenize_sentences == NULL) {
            validateSignature("Rcpp::List(*tokenize_sentences)(Rcpp::CharacterVector)");
            p_tokenize_sentences = (Ptr_tokenize_sentences)R_GetCCallable("RcppKagome", "_RcppKagome_tokenize_sentences");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_tokenize_sentences(Shield<SEXP>(Rcpp::wrap(text)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

}

#endif // RCPP_RcppKagome_RCPPEXPORTS_H_GEN_
