// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppKagome.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// tokenize_morphemes
Rcpp::CharacterVector tokenize_morphemes(Rcpp::CharacterVector text);
static SEXP _RcppKagome_tokenize_morphemes_try(SEXP textSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type text(textSEXP);
    rcpp_result_gen = Rcpp::wrap(tokenize_morphemes(text));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _RcppKagome_tokenize_morphemes(SEXP textSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_RcppKagome_tokenize_morphemes_try(textSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _RcppKagome_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("Rcpp::CharacterVector(*tokenize_morphemes)(Rcpp::CharacterVector)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _RcppKagome_RcppExport_registerCCallable() { 
    R_RegisterCCallable("RcppKagome", "_RcppKagome_tokenize_morphemes", (DL_FUNC)_RcppKagome_tokenize_morphemes_try);
    R_RegisterCCallable("RcppKagome", "_RcppKagome_RcppExport_validate", (DL_FUNC)_RcppKagome_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppKagome_tokenize_morphemes", (DL_FUNC) &_RcppKagome_tokenize_morphemes, 1},
    {"_RcppKagome_RcppExport_registerCCallable", (DL_FUNC) &_RcppKagome_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppKagome(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
