# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Trigger kagome tokenizer
#'
#' For internal use. The argument should be UTF8 encoded. This function just
#' returns an UTF8-encoded json as character scalar.
#'
#' @param text character vector
#' @return res character scalar (JSON string)
#'
#' @name tokenize
#' @keywords internal
#' @export
NULL

tokenize <- function(text) {
    .Call('_RcppKagome_tokenize', PACKAGE = 'RcppKagome', text)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_RcppKagome_RcppExport_registerCCallable', PACKAGE = 'RcppKagome')
})
