# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Trigger kagome tokenizer
#'
#' For internal use. The argument should be UTF8 encoded. This function just
#' returns UTF8-encoded json strings as a character vector.
#'
#' @param text Character vector.
#' @return Character vector (JSON strings).
#'
#' @name tokenize_morphemes
#' @keywords internal
#' @export
NULL

#' Split sentence
#'
#' For internal use. The argument should be UTF8 encoded.
#'
#' @param text Character vector.
#' @return List.
#'
#' @name tokenize_sentences
#' @keywords internal
#' @export
NULL

#' Tiny Segmenter
#'
#' For internal use. The argument should be UTF8 encoded.
#'
#' @param text Character vector.
#' @return Character vector.
#'
#' @name tokenize_segments
#' @keywords internal
#' @export
NULL

tokenize_morphemes <- function(text) {
    .Call(`_RcppKagome_tokenize_morphemes`, text)
}

tokenize_sentences <- function(text) {
    .Call(`_RcppKagome_tokenize_sentences`, text)
}

tokenize_segments <- function(text) {
    .Call(`_RcppKagome_tokenize_segments`, text)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_RcppKagome_RcppExport_registerCCallable', PACKAGE = 'RcppKagome')
})
