# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Triggers kagome tokenizer
#'
#' For internal use. The argument should be UTF8 encoded. This function just
#' returns an UTF8-encoded json as a character scalar.
#'
#' @param text Character vector.
#' @return res Character scalar (JSON string).
#'
#' @name tokenize_morphemes
#' @keywords internal
#' @export
NULL

tokenize_morphemes <- function(text) {
    .Call(`_RcppKagome_tokenize_morphemes`, text)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_RcppKagome_RcppExport_registerCCallable', PACKAGE = 'RcppKagome')
})
