name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        r-version: ['4.0.0']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install libcurl-dev
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_github("r-lib/covr")
          remotes::install_github("gaborcsardi/async")
          remotes::install_github("paithiov909/kagomer")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Update submodules
        run: |
          git submodule init
          git submodule update --recommend-shallow --recursive
      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-multiarch", "--no-vignettes", "--no-manual"), build_args = c("--no-build-vignettes", "--no-manual"), error_on = "error")
        shell: Rscript {0}
      - name: Codecov
        run: covr::codecov()
        shell: Rscript {0}