name: R-CMD-check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  check:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        r-version: ['release']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install libcurl-dev
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "covr"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Install Kagome
        run: go install github.com/ikawaha/kagome/v2@latest
      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-multiarch", "--no-vignettes", "--no-manual", "--as-cran"), build_args = c("--no-build-vignettes", "--no-manual"), error_on = "error")
        shell: Rscript {0}
      - name: Codecov
        run: covr::codecov()
        shell: Rscript {0}
