name: R-CMD-build

on:
  push:
    branches: [ $default-branch ]
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]
        r-version: ['4.0.0']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "pkgbuild"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Draft release
        id: release_pr
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Build binary package
        run: |
          Rscript -e "pkgbuild::build('.', dest_path = '.', args = '--no-multiarch', binary = TRUE)"
          ren *.zip temp.zip
      - name: Upload binary package
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_pr.outputs.upload_url }}
          asset_path: temp.zip
          asset_name: RcppKagome.zip
          asset_content_type: application/zip
